### ISSUE TITLE
Add a note about the plugin name

### ISSUE THREAD

**Issue by martonmiklos** [martonmiklos/rqt_plugin_wizard_for_qtcreator#2]
That it is going to be prefixed with rqt_ (to prevent rqt_rqt_foobar plugins to be created.)

**Comment by ConnorNovak** [comment]
Might be worth noting that the folder created within the catkin_ws will be named without the rqt_ prefix . . . this confused me for a bit.

**Comment by martonmiklos** [comment]
@ConnorNovak 

I have separated the plugin path, plugin name, and the (main) class name fields. 
I have also added validation, so I think it should be straightforward now.
