### ISSUE TITLE
Error or misconfiguration?

### ISSUE THREAD

**Issue by melvinisken** [martonmiklos/rqt_plugin_wizard_for_qtcreator#4]
I'm quite new to Qt / rqt programming, so I don't know if this is an issue with the plugin or my setup:
On a completely fresh setup of Ubuntu 18.04, ROS Melodic, Qt 5.13.0 (newest version of online installer today, installed to /opt/Qt) I was not able to compile the generated package without adding these lines to CMakeLists.txt:

```
set(QT_VERSION 5.13.0)
set(QT_ROOT /opt/Qt/${QT_VERSION})
set(QT_LIBRARIES        ${QT_ROOT}/gcc_64/lib)
set(QT_INCLUDE_DIRS     ${QT_ROOT}/gcc_64/include)
set(CMAKE_PREFIX_PATH   ${QT_ROOT}/gcc_64/lib/cmake/Qt5)
```

So is it a necessity for each package I create with this plugin to add these lines manually or an issue with my configuration? 
I created the standard empty workspace catkin_ws and added the setup.bash to the .bashrc. (completely following the standard ROS setup tutorials). Afterwards I created a test package using qtcreator (I used the qtcreator bundle with ROS plugin, not the one delivered with the Qt installation). Would be great to get some insight if/what I'm doing wrong here.

**Comment by martonmiklos** [comment]
Hi @melvinisken 

As far as I know (by default) catkin uses the Qt version shipped with the distribution itself. (qtbase5-dev and similar).

**Comment by melvinisken** [comment]
Yes, cool, that solved it. After installing qtbase5-dev it compiles without those extra lines in CMakeLists.txt. Thanks!
