### ISSUE TITLE
Created file discrepancies

### ISSUE THREAD

**Issue by melvinisken** [martonmiklos/rqt_plugin_wizard_for_qtcreator#5]
Another newbe finding: When I look at the freshly created file structure in qtcreator and on disk, there seems to be a difference. In qtcreator, I have a file named test_plugin.config listed, which doesn't exist on disk (I also get an error when I click on it), where on my disk I have test_plugin.creator, which doesn't exist in the qtcreator-project. Should it be like this?

![image](https://user-images.githubusercontent.com/10966010/60760371-b52ed680-a034-11e9-9938-af0b5e071634.png)

![image](https://user-images.githubusercontent.com/10966010/60760377-c1b32f00-a034-11e9-8287-d0e6755ddd66.png)

**Comment by martonmiklos** [comment]
Good catch!

The config file is not really necessary (feel free to remove it from the project until I fix it)

(The .config file is used to add predefined macros for your imprted project. But in the case if you compile your rqt plugin with catkin_make it is irrelevant. )

BTW. you mentioned that you are newcomer to this, this is how I used to setup my rqt plugin building process:

- Start the QtCreator from an env where the catkin env is setup properly (setup.sh is sourced)
- Create the project
- Remove the make step add a custom build step like this one:
![kép](https://user-images.githubusercontent.com/1609182/60760472-23c06400-a036-11e9-94a2-5161baff0eb3.png)

To the run configuration add  the following:
![kép](https://user-images.githubusercontent.com/1609182/60760484-536f6c00-a036-11e9-999d-ab778361aa5b.png)

With this setup you can even debug your plugin with GDB.

**Comment by xakod** [comment]
> Good catch!
> 
> The config file is not really necessary (feel free to remove it from the project until I fix it)
> 
> (The .config file is used to add predefined macros for your imprted project. But in the case if you compile your rqt plugin with catkin_make it is irrelevant. )
> 
> BTW. you mentioned that you are newcomer to this, this is how I used to setup my rqt plugin building process:
> 
>     * Start the QtCreator from an env where the catkin env is setup properly (setup.sh is sourced)
> 
>     * Create the project
> 
>     * Remove the make step add a custom build step like this one:
>       ![kép](https://user-images.githubusercontent.com/1609182/60760472-23c06400-a036-11e9-94a2-5161baff0eb3.png)
> 
> 
> To the run configuration add the following:
> ![kép](https://user-images.githubusercontent.com/1609182/60760484-536f6c00-a036-11e9-999d-ab778361aa5b.png)
> 
> With this setup you can even debug your plugin with GDB.

I followed you instruction, setup everything
![Screenshot from 2019-09-20 15-35-33](https://user-images.githubusercontent.com/26579016/65327359-71238a80-dbbc-11e9-9e31-9a628ce3c97f.png)

It built ok

> 15:34:50: Starting: "/opt/ros/melodic/bin/catkin_make" --pkg=rqt_my_pkg
>[ 37%] Generating include/rqt_my_pkg/moc_rqt_my_pkg_widget.cpp
>[ 37%] Generating ui_rqt_my_pkg_widget.h
>[ 37%] Generating include/rqt_my_pkg/moc_rqt_my_pkg.cpp
/home/atom/test_ws/src/my_pkg/include/rqt_my_pkg/rqt_my_pkg.h:0: Note: No relevant classes found. No output generated.
>Scanning dependencies of target rqt_my_pkg
>[ 50%] Building CXX object my_pkg/CMakeFiles/rqt_my_pkg.dir/src/rqt_my_pkg/rqt_my_pkg.cpp.o
>[ 62%] Building CXX object my_pkg/CMakeFiles/rqt_my_pkg.dir/include/rqt_my_pkg/moc_rqt_my_pkg_widget.cpp.o
>[ 75%] Building CXX object my_pkg/CMakeFiles/rqt_my_pkg.dir/src/rqt_my_pkg/rqt_my_pkg_widget.cpp.o
>[ 87%] Building CXX object my_pkg/CMakeFiles/rqt_my_pkg.dir/include/rqt_my_pkg/moc_rqt_my_pkg.cpp.o
>[100%] Linking CXX shared library /home/atom/test_ws/devel/lib/librqt_my_pkg.so
>[100%] Built target rqt_my_pkg
>Base path: /home/atom/test_ws
>Source space: /home/atom/test_ws/src
>Build space: /home/atom/test_ws/build
>Devel space: /home/atom/test_ws/devel
>Install space: /home/atom/test_ws/install
>####
>#### Running command: "make cmake_check_build_system" in "/home/atom/test_ws/build"
>####
>####
>#### Running command: "make -j4 -l4" in "/home/atom/test_ws/build/my_pkg"
>####
>15:34:53: The process "/opt/ros/melodic/bin/catkin_make" exited normally.
>15:34:53: Elapsed time: 00:03.

But when i had tried to run with rqt i catched this 

> [ERROR] [1568982913.966360392]: Failed to load nodelet [my_pkg_1] of type [my_pkg]: Failed to load library /home/atom/test_ws/devel/lib//librqt_my_pkg.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.13' not found (required by /home/atom/test_ws/devel/lib//librqt_my_pkg.so))
> RosPluginlibPluginProvider::load_explicit_type(my_pkg) failed creating instance
> PluginManager._load_plugin() could not load plugin "my_pkg": RosPluginlibPluginProvider.load() could not load plugin "my_pkg"

> atom@notebook:~$ ls  /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
> /usr/lib/x86_64-linux-gnu/libQt5Core.so.5

It's default project of course

**Comment by martonmiklos** [comment]
What Qt version do you have installed to  /usr/lib/x86_64-linux-gnu/libQt5Core.so.5?

Please post an` ldd /home/atom/test_ws/devel/lib//librqt_my_pkg.so` output.
