### ISSUE TITLE
issue with make

### ISSUE THREAD

**Issue by xakod** [martonmiklos/rqt_plugin_wizard_for_qtcreator#6]
Hello. I cloned repo into templates. Created new project following the instruction. Tried to compile
> 01:35:23: Running steps for project untitled1...
> 01:35:23: Starting: "/usr/bin/make" -j4 all
> make: *** No rule to make target 'all'.  Stop.
> 01:35:23: The process "/usr/bin/make" exited with code 2.
> Error while building/deploying project untitled1 (kit: Clone of Desktop)
> When executing step "Make"
> 01:35:23: Elapsed time: 00:00.

Make gave me error

**Comment by martonmiklos** [comment]
Hey @Jihadist 

rqt plugins needs to be built with catkin_make not the make. 
This is how I used to build ros packages with QtCreator:
https://github.com/martonmiklos/rqt_plugin_wizard_for_qtcreator/issues/5#issuecomment-508949122

Let me know if it works for you. I might add this info to the README.md as well.
