### ISSUE TITLE
Separate .cpp and .h files for app and widget

### ISSUE THREAD

**Issue by Riconec** [martonmiklos/rqt_plugin_wizard_for_qtcreator#7]
Why it is done that way, so I have 4 files: my_pkg.cpp, my_pkg.h and my_pkg_widget.cpp, my_pkg_widget.h?

Why not to use only one pair?

I am struggling to subscribe to message and update an UI based on data from ros message... The reason is I need to define a callback in namespace of plugin, but from there the UI elements aren't accessible with error `error: invalid use of incomplete type ‘class Ui::my_pkgWidget’` and ` note: forward declaration of ‘class Ui::my_pkgWidget’` because on compile time it don't know about pointer to QT UI widget

this is what I am trying to do in callback : 
`this->widget->ui->ObjectNumDisplay.intValue(message.metadata.n_objects);` 

Definitely I am doing it wrong, but the plugin template looks overcomplicated in comparison with templates from ROS

**Comment by martonmiklos** [comment]
> Definitely I am doing it wrong, but the plugin template looks overcomplicated in comparison with templates from ROS

Could you please point out to the mentioned templates? If I remember correctly the rqt_image_view was the plugin where I got the most of the inspiration when I first created it, and as checking the current state of that plugin this still valid: they have a separate plugin (image_view) and widget class  (ratio_layouted_frame):
https://github.com/ros-visualization/rqt_image_view/tree/master/src/rqt_image_view

>  The reason is I need to define a callback in namespace of plugin

Why?
I have some plugins where I simply subscribed to topics in my UI code:

```
  statusSubscriber.shutdown(); // unsubscribe first
    statusSubscriber = m_nodeHandle.subscribe("/tiva_arm/armState", 1, &RobotArmConfigWidget::statusCallback, this);

....

void RobotArmConfigWidget::statusCallback(const rescube_msgs::RobotARMStatus::ConstPtr &msg)
{
    boost::mutex::scoped_lock lock(m_refreshMutex, boost::try_to_lock);
    if (lock) {
        m_statusMessage = msg;
    }
}


```

**Comment by Riconec** [comment]
I am unable to create subsriber\publisher from widget, thus I stuck with communication part in plugin part. GetNodeHandle is not working here

What I need to do to be able to use messages from widget (ui) part of code?

**Comment by Riconec** [comment]
And also, can you point me to the repo with callback in widget part you mentioned?

**Comment by martonmiklos** [comment]
> I am unable to create subsriber\publisher from widget, thus I stuck with communication part in plugin part. GetNodeHandle is not working here

I simply used a ros::NodeHandle member for subscribe/publish.

> And also, can you point me to the repo with callback in widget part you mentioned?

It's in a private repo, thus here is a tarball from it:
[rqt_robot_arm_config.tar.gz](https://github.com/martonmiklos/rqt_plugin_wizard_for_qtcreator/files/3939545/rqt_robot_arm_config.tar.gz)

You can find the subscription in the constructor in the robot_arm_config_widget.cpp

**Comment by martonmiklos** [comment]
@Riconec have you managed to sort your issue out?

**Comment by Riconec** [comment]
Sorry for the late reply.

I thought  that in rqt plugins I should use getNodeHandle (to use one created by rqt), didn't even think about just creating node. 

On the short trial - I am able to create a node and publisher from widget class. 

I think we can close issue, I will reopen if something related will happen.

Thanks a lot for help!
